### PR TITLE
update shell

### PR DESCRIPTION
**Pull request by ragu-1997**
Add procedural shell format

### CODE REVIEW

**Comment by Marusyk** [comment]
Hi, what does it mean?

> (good-first-issue-(good-first-issue)

**Comment by ragu-1997** [comment]
Hi,
Sorry unfortunately i mentioned a label

**Review by Marusyk — APPROVED** [review]

**Comment by Marusyk** [comment]
@ragu-1997 please fix the editorconfig warning

**Review by Marusyk — CHANGES_REQUESTED** [review]
Please fix the editorconfig warning

**Comment by ragu-1997** [comment]
Ok, I will check.

**Comment by ragu-1997** [comment]
Field Names Must Not Begin With Underscore in the .editorconfig. Along with the attribute you documented, it would be helpful if how to setup it up in the .editorconfig file.

**Comment by ragu-1997** [comment]
Please approved the request I'll mention some points

**Pull request closed without merging**
