### PR TITLE
upgrading to .net 7.0.101

### PR DESCRIPTION
**Pull request by alinizam723**
PR for #64 
I am a newbie to this and have tried to upgrade for the first time. Please have a close look.

### CODE REVIEW

**Comment by Marusyk** [comment]
Hi @alinizam723 
thank you for your contribution. as you may see, builds fails, they should be also changed. Please check if we need to upgrade NuGet packages

**Review by Marusyk — CHANGES_REQUESTED** [review]
Hi @alinizam723
thank you for your contribution. as you may see, builds fails, they should be also changed. Please check if we need to upgrade NuGet packages

**Comment by Marusyk** [comment]
Hi @alinizam723
are you going to fix this?

**Comment by alinizam723** [comment]
the code is building fine on my machine. I am not sure if the build machine has .net 7.0

**Comment by Marusyk** [comment]
yes, exactly, that's what you should fix in scope of this PR

**Comment by Marusyk** [comment]
done in https://github.com/Marusyk/grok.net/pull/70

**Pull request closed without merging**
