### PR TITLE
Added pattern for base64 string

### PR DESCRIPTION
**Pull request by nik-base**
Changes required for #58

### CODE REVIEW

**Review by Marusyk — APPROVED** [review]
LGTM 👍 Thank you for your contribution

**Review by Marusyk — CHANGES_REQUESTED** [review]
Pls fix codestyle

**Comment by nik-base** [comment]
@Marusyk , I have updated files in commit to conform to coding style.

All the existing files in the repo are failing the PR Audit, maybe this is because the GitHub action used for this has changed the rules?

**Review by Marusyk — APPROVED** [review]

**Comment by Marusyk** [comment]
@nik-base your changes have been merged, thanks for your contribution 👍

**Pull request merged**
